### ISSUE TITLE
Virtual background effect spams debug messages for every frame

### ISSUE THREAD

**Issue by GMacAussie** [nexmo-se/video-api-effects#14]
Reference:

https://github.com/nexmo-se/video-api-effects/blob/9a929f1873f4c17d8844cd006fa51f9e605129ec/lib/effects/background/VirtualBackgroundEffect.ts#L76

Can this be change to either:
1. Remove the debug
2. Change the default log level
3. Expose the log level in the background effect processor so we can change it ourselves

It makes our own debugging difficult...

**Comment by brian17han** [comment]
Hi,
I changed the logLevel to something above "Debug" in the main js file to make this not show up. I think they expect you to set the "process.env.NODE_ENV === 'production'" to set "log.setLevel('WARN')". However, I am using GWT so I can't set this.

**Comment by GMacAussie** [comment]
With release 1.0.0 the debug statements have been removed/commented out. Closing this ticket.
