### ISSUE TITLE
`publisher.setVideoSource` not changing video source

### ISSUE THREAD

**Issue by AriHrannar** [nexmo-se/video-api-effects#15]
Hi,

When I initialise the publisher I am setting the `videoSource` as `effectProcessor.outputStream.getVideoTracks()[0]` as per the documentation.

Then we have another feature where you can change your camera from f.x. the internal laptop one to an external camera. Here we use [OT.getDevices](https://tokbox.com/developer/sdks/js/reference/OT.html#getDevices) and get a list of devices, we then filter by `kind` for `videoInput` and then we have a list of video inputs. Then each video input has a `deviceId`, which we then send to  [publisher.setVideoSource](https://tokbox.com/developer/guides/audio-video/js/#switch_camera) to change the camera.

However, when I call `publisher.setVideoSource` with a device id, the video source is not changed.

Here you can see the code where I am logging the device id and then the result of `getVideoSource` before and after `setVideoSource` is called

![image](https://user-images.githubusercontent.com/6696198/165725914-690b18dc-bc27-4081-975c-daa87e884184.png)

Here you can see the result, the video source is unchanged. The `deviceId` is also null here, perhaps that is part of the problem, I would expect this to be the id of the video source device where the background is being changed :)

<img width="600" alt="image" src="https://user-images.githubusercontent.com/6696198/165726317-de161a0c-af57-448f-9158-3263745aad85.png">

Im running
"@opentok/client": "2.22.2"
"@vonage/video-effects": "1.0.0-rc3",

I hope that is clear enough, let me know if something is unclear :)

**Comment by brian17han** [comment]
In their [developer doc](https://tokbox.com/developer/sdks/js/reference/Publisher.html#setVideoSource), it states setVideoSource will not work "If the publisher does not currently use a camera input, the promise will reject with an error with the name property set to 'OT_SET_VIDEO_SOURCE_FAILURE'." 
I agree this is definitely something we need so we can change videoSource once the publisher is started. My workaround is to use "backgroundEffectProcessor.setInputStream(mediaStream);" to change the stream to the other camera.

**Comment by enricop89** [comment]
Yes, using the `backgroundEffectProcessor.setInputStream(mediaStream);` is the right approach
